### ISSUE TITLE
Отсутствуют картинки в статье "Fault tolerance и его реализация в PHP"

### ISSUE THREAD

**Issue by stepanov** [golotyuk/ruhighload#4]
Не грузятся картинки в статье Fault tolerance и его реализация в PHP:

`403 Forbidden`

Пример - https://i.onthe.io/shpzkl2de3ecamnkig.8d788fc7.jpg

**Comment by golotyuk** [comment]
Фиксд

**Comment by stepanov** [comment]
Подтверждаю! Спасибо за отличный ресурс! И очень быстрый фикс ;)
